apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-wine-configs-database
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team15
  target:
    name: database-pass
    creationPolicy: Owner
  data:
    - secretKey: CONNECTION_URL
      remoteRef:
        key: kv/data/team15/database
        property: CONNECTION_URL