apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-wine-configs-jwt
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team15
  target:
    name: jwt-pass
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: kv/data/team15/jwt
        property: SECRET_KEY