apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-wine-configs-queue
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team15
  target:
    name: rabbitmq-pass
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: kv/data/team15/k8s
        property: RABBITMQ_DEFAULT_PASS
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: kv/data/team15/k8s
        property: RABBITMQ_DEFAULT_USER