version: "3"

services:
  app:
    build: ./live/app/
    image: python3.9-slim:latest
    env_file:
      - ./live/app/.env
    volumes:
      - ./live/app:/app
      - ./source/models:/models/
      - ./source/data:/data/
    command: python app.py
    depends_on:
      rabbitmq:
        condition: service_started
      prodpostgres:
        condition: service_started
    restart: on-failure

  worker:
    build: ./live/app/
    deploy:
      mode: replicated
      replicas: 3
    env_file:
      - ./live/app/.env
    volumes:
      - ./live/app:/app
      - ./source/models:/models/
      - ./source/data:/data/
    command: python ml/rmworkers.py
    depends_on:
      app:
        condition: service_started
    restart: on-failure

  web-proxy:
    build: ./live/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  prodpostgres:
    image: postgres:13.3
    hostname: prodpostgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432