apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: main-app

spec:
  ports:
    - name: {{ .Release.Name }}-base-port
      port: 80
      targetPort: 8081
  selector:
    app: main-app