apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:

  RABBIT_HOST: "{{ .Release.Name }}-rabbitmq"
  RABBIT_PORT: "5672"
  RABBIT_QUEUE: "message"

  COOKIE_NAME: "cookie_name"
  DATA_ROOT_PATH: "/data"

  BACKEND_HOST: "http://{{ .Release.Name }}-app:80"