apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-restricted-role
  namespace: {{ .Release.Namespace | default "team15-ns" }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-app-binding
  namespace: {{ .Release.Namespace | default "team15-ns" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-app
    namespace: {{ .Release.Namespace | default "team15-ns" }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-restricted-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-worker-binding
  namespace: {{ .Release.Namespace | default "team15-ns" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-worker
    namespace: {{ .Release.Namespace | default "team15-ns" }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-restricted-role
  apiGroup: rbac.authorization.k8s.io
