apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "{{ .Values.rabbitmq.auth.username }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.rabbitmq.auth.password }}"
  RABBIT_USER: "{{ .Values.rabbitmq.auth.username }}"
  RABBIT_PASSWORD: "{{ .Values.rabbitmq.auth.password }}"

  POSTGRES_PASSWORD: "{{ .Values.postgres.auth.password }}"

  SECRET_KEY: "123123"
  CONNECTION_URI: "postgresql+psycopg2://{{ .Values.postgres.auth.user }}:{{ .Values.postgres.auth.password }}@79.174.89.43:18809/{{ .Values.postgres.auth.db }}"