apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace | default "team15-ns" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace | default "team15-ns" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-webui
  namespace: {{ .Release.Namespace | default "team15-ns" }}
