image:
  repository: kursornn/wine-detector
  tag: v61
  pullPolicy: IfNotPresent

worker:
  replicas: 4

rabbitmq:
  image: rabbitmq:3.13.3-management
  auth:
    username: admin
    password: admin

postgres:
  image: postgres:13.3
    #auth:
    #db: team15_db
  #user: team15
  #password: Gy4pVhT6#b9Dc1wM
  port: 18809
  host: 79.174.89.43

ingress:
  enabled: true
  host: team15.kubepractice.ru
  className: nginx

resources:
  main:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
  rabbitmq:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 1Gi

monitoring:
  enabled: true

kube-prometheus-stack:
  grafana:
    enabled: false

  alertmanager:
    enabled: false

  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "standard"
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi