name: Build and push Docker images

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io  # ???
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          context: ./live/app
          file: ./live/app/Dockerfile
          push: true
          tags: |
            ivan5024/app:latest
            ivan5024/app:v${{ github.run_number }}

      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./live/nginx
          file: ./live/nginx/Dockerfile
          push: true
          tags: |
            ivan5024/nginx:latest
            ivan5024/nginx:v${{ github.run_number }}
